python: 2.7

install:
  - echo "Install..."
  - pip install -U uiautomator -i http://pipy.douban.com/simple

before_script:
  - echo "Before script..."

script:
  - python test.py

after_script:
  - echo "after_script"
