lang: python

python: 2.7

env:
  list-field: [1, 2, 3, 4, 5]
  fix-field:
    options: ['a', 'b', 'c']
    fix: true
  exclusive:
    fix: false
    exclusive: false

install:
  - echo "Install..."
  - pip install -M -U uiautomator -i http://pypi.douban.com/simple

before_script:
  - echo "Before script..."

script:
  - python test.py

after_script:
  - echo "after_script"
